FLAGS = {
    "DISCORD_EMPLOYEE": 1 << 0,
    "PARTNERED_SERVER_OWNER": 1 << 1,
    "HYPESQUAD_EVENTS": 1 << 2,
    "BUG_HUNTER_LEVEL_1": 1 << 3,
    "BRAVERY": 1 << 6,
    "BRILLIANCE": 1 << 7,
    "BALANCE": 1 << 8,
    "EARLY_SUPPORTER": 1 << 9,
    "BUG_HUNTER_LEVEL_2": 1 << 14,
    "VERIFIED_BOT_DEVELOPER": 1 << 17,
    "CERTIFIED_MODERATOR": 1 << 18
}